# Generated by Django 5.2.5 on 2025-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0002_remove_entry_register_line_entry_entry_edition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('entry_date', models.DateField(verbose_name='date of entry')),
                ('entry_author', models.CharField(max_length=100)),
                ('entry_title', models.CharField(max_length=500)),
                ('entry_volumes', models.CharField(blank=True, max_length=100)),
                ('entry_edition', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
