# Generated by Django 5.2.5 on 2025-08-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0003_libraryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryentry',
            name='library_name',
        ),
        migrations.CreateModel(
            name='LibraryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_library', models.CharField(choices=[('BOL', 'Bodleian Library'), ('BRL', 'British Library'), ('CAL', 'Cambridge Library'), ('SCL', 'National Library of Scotland'), ('TRL', 'Trinity College Dublin Library')], default='BRL', max_length=3)),
                ('collection_start_date', models.DateField(verbose_name='collection start date')),
                ('collection_end_date', models.DateField(verbose_name='collection end date')),
                ('target_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationers.register')),
            ],
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='library_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stationers.librarycollection'),
        ),
    ]
