# Generated by Django 5.2.5 on 2025-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0004_remove_libraryentry_library_name_librarycollection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryentry',
            name='library_collection',
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='source_library',
            field=models.CharField(choices=[('BOL', 'Bodleian Library'), ('BRL', 'British Library'), ('CAL', 'Cambridge Library'), ('SCL', 'National Library of Scotland'), ('TRL', 'Trinity College Dublin Library')], default='BRL', max_length=3),
        ),
        migrations.DeleteModel(
            name='LibraryCollection',
        ),
    ]
