# Generated by Django 5.2.5 on 2025-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0005_remove_libraryentry_library_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='confirmed_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='library_entry',
            field=models.ManyToManyField(to='stationers.libraryentry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='match_type',
            field=models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('NON', 'No match')], default='NON', max_length=3),
        ),
    ]
