# Generated by Django 5.2.5 on 2025-08-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0006_entry_confirmed_match_entry_library_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='library_entry',
            new_name='matching_library_entry',
        ),
    ]
