# Generated by Django 5.2.5 on 2025-08-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0007_rename_library_entry_entry_matching_library_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='confirmed_match',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='matching_library_entry',
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('NON', 'No match')], default='NON', max_length=3)),
                ('confirmed', models.BooleanField(default=False)),
                ('library_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stationers.libraryentry')),
                ('register_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationers.entry')),
            ],
        ),
    ]
