# Generated by Django 5.2.5 on 2025-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0008_remove_entry_confirmed_match_remove_entry_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='register',
            field=models.ManyToManyField(to='stationers.register'),
        ),
    ]
