# Generated by Django 5.2.5 on 2025-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0009_libraryentry_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='entry',
            name='confirmed_match',
            field=models.BooleanField(default=False),
        ),
    ]
