# Generated by Django 5.2.5 on 2025-08-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0010_remove_matches_confirmed_entry_confirmed_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='register_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register_pages',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register_start_date',
            new_name='start_date',
        ),
    ]
