# Generated by Django 5.2.5 on 2025-08-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0011_rename_register_end_date_register_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_edition',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_volumes',
            new_name='volumes',
        ),
        migrations.RenameField(
            model_name='libraryentry',
            old_name='entry_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='libraryentry',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='libraryentry',
            old_name='entry_edition',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='libraryentry',
            old_name='entry_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='libraryentry',
            old_name='entry_volumes',
            new_name='volumes',
        ),
    ]
