# Generated by Django 5.2.5 on 2025-08-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0012_rename_entry_author_entry_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='MatchCandidate',
        ),
    ]
