# Generated by Django 5.2.5 on 2025-08-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0013_rename_matches_matchcandidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='RegisterEntry',
        ),
    ]
