# Generated by Django 5.2.5 on 2025-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0014_rename_entry_registerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcandidate',
            name='confirmed_match',
            field=models.BooleanField(default=False),
        ),
    ]
