# Generated by Django 5.2.5 on 2025-08-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0016_registerentry_library_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerentry',
            name='library_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationers.libraryentry'),
        ),
    ]
