# Generated by Django 5.2.5 on 2025-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0017_alter_registerentry_library_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchcandidate',
            old_name='confirmed_match',
            new_name='human_checked',
        ),
        migrations.RenameField(
            model_name='registerentry',
            old_name='confirmed_match',
            new_name='human_checked',
        ),
        migrations.AlterField(
            model_name='matchcandidate',
            name='match_type',
            field=models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('FZP', 'Fuzzy partial match'), ('NON', 'No match')], default='NON', max_length=3),
        ),
    ]
