# Generated by Django 5.2.5 on 2025-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0018_rename_confirmed_match_matchcandidate_human_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchcandidate',
            name='human_checked',
        ),
        migrations.RemoveField(
            model_name='registerentry',
            name='human_checked',
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='match_confirmed',
            field=models.CharField(choices=[('NOT', 'Not confirmed'), ('YES', 'Confirmed'), ('REJ', 'Rejected')], default='NOT', max_length=3),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='match_confirmed',
            field=models.CharField(choices=[('NOT', 'Not confirmed'), ('YES', 'Confirmed'), ('REJ', 'Rejected')], default='NOT', max_length=3),
        ),
        migrations.AlterField(
            model_name='matchcandidate',
            name='match_type',
            field=models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('FZP', 'Fuzzy partial match')], default='EXC', max_length=3),
        ),
    ]
