# Generated by Django 5.2.5 on 2025-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0019_remove_matchcandidate_human_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcandidate',
            name='match_type',
            field=models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('FZP', 'Fuzzy partial match')], default='EXC', max_length=3, null=True),
        ),
    ]
