# Generated by Django 5.2.5 on 2025-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0020_alter_matchcandidate_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcandidate',
            name='match_type',
            field=models.CharField(choices=[('EXC', 'Exact match'), ('PAR', 'Partial match'), ('FUZ', 'Fuzzy match'), ('FZP', 'Fuzzy partial match')], max_length=3, null=True),
        ),
    ]
