# Generated by Django 5.2.5 on 2025-08-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0021_alter_matchcandidate_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerentry',
            name='library_entry',
        ),
        migrations.RemoveField(
            model_name='registerentry',
            name='match_confirmed',
        ),
    ]
