# Generated by Django 5.2.5 on 2025-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0022_remove_registerentry_library_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='source_library',
            field=models.CharField(choices=[('BDL', 'Bodleian Library'), ('BTL', 'British Library'), ('CAL', 'Cambridge Library'), ('NLS', 'National Library of Scotland'), ('TCD', 'Trinity College Dublin Library')], default='BTL', max_length=3),
        ),
    ]
