# Generated by Django 5.2.5 on 2025-10-31 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0023_alter_libraryentry_source_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryentry',
            name='date',
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='max_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 12, 56, 50, 50734), verbose_name='latest date of entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='min_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 12, 56, 57, 627542), verbose_name='earliest date of entry'),
            preserve_default=False,
        ),
    ]
