# Generated by Django 5.2.5 on 2025-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0025_alter_libraryentry_max_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='max_date',
            field=models.DateField(blank=True, null=True, verbose_name='latest date of entry'),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='min_date',
            field=models.DateField(blank=True, null=True, verbose_name='earliest date of entry'),
        ),
    ]
