# Generated by Django 5.2.5 on 2025-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0026_alter_libraryentry_max_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcandidate',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
