# Generated by Django 5.2.5 on 2025-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0027_matchcandidate_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerentry',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='date',
            field=models.DateField(null=True, verbose_name='date of entry'),
        ),
    ]
