# Generated by Django 5.2.5 on 2025-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0028_alter_registerentry_author_alter_registerentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryentry',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='register end date'),
        ),
        migrations.AlterField(
            model_name='register',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='register_pdfs'),
        ),
        migrations.AlterField(
            model_name='register',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='register start date'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='volumes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
