# Generated by Django 5.2.5 on 2025-11-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0029_alter_libraryentry_author_alter_register_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryentry',
            old_name='author',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='registerentry',
            old_name='author',
            new_name='creator',
        ),
    ]
