# Generated by Django 5.2.5 on 2025-11-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0030_rename_author_libraryentry_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerentry',
            old_name='creator',
            new_name='publisher',
        ),
    ]
