# Generated by Django 5.2.5 on 2025-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0031_rename_creator_registerentry_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerentry',
            name='register_page',
        ),
        migrations.AddField(
            model_name='registerentry',
            name='block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='clean_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='creator',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
