# Generated by Django 5.2.5 on 2025-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0032_remove_registerentry_register_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryentry',
            name='artifact_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='artifact_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='clean_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='contributor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='coverage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='date_string',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='identifier',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='publisher',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='relation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='rights',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libraryentry',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='libraryentry',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
