# Generated by Django 5.2.5 on 2025-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0034_alter_libraryentry_clean_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerentry',
            name='clean_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='creator',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
